fix #138 countries graphql errors on explode
hyva-themes/magento2-hyva-checkout pull request #139
Opened 2021-08-11 13:27 UTC by peterschriever

Hello, this PR fixes the throwing of an error when `general/region/state_required` isnt configured or is empty. In such cases it would now return an empty array for the countries of which state should be required.

We still need to document how and that developers should appropriately configure this option though!

as described in #138

2021-08-12 05:57 UTC, schmengler requested changes

2021-08-12 05:57 UTC, schmengler commented on src/Plugin/DirectoryModel/SetStateRequired.php
> +            if (!$configStateRequired) return [];
That will work but let's always save the value in `$this->stateRequiredCountries`

A more simple fix would be:
```
            $this->stateRequiredCountries = explode(',', (string) $this->scopeConfig->getValue(
                'general/region/state_required',
                ScopeInterface::SCOPE_STORES,
                $store->getCode()
            ));
```

no additional variables, still a single return point

2021-08-12 07:03 UTC, peterschriever commented
Do u mean putting an empty array inside `$this->stateRequiredCountries` ? And then having the explode in an else?

The reason explode throws an error here is because '$this->scopeConfig->getValue' returns a null value. Even with the `(string)` tag i believe. Another option would be a try catch, but i thought an early return to be the cleanest and most simple.

2021-08-12 07:25 UTC, progammer-rkt commented
> Do u mean putting an empty array inside `$this->stateRequiredCountries` ? And then having the explode in an else?
> 
> The reason explode throws an error here is because '$this->scopeConfig->getValue' returns a null value. Even with the `(string)` tag i believe. Another option would be a try catch, but i thought an early return to be the cleanest and most simple.

@peterschriever  The error in the issue says: `explode() expects parameter 2 to be string, null given`. So turning `null` to an empty string would work. So `(string)` will work for sure. But still the suggested solution will provide `['']` as its ouput. ie, array is not really empty. So the correct code would be:

```
$this->stateRequiredCountries = array_filter(explode(',', (string) $this->scopeConfig->getValue(
                'general/region/state_required',
                ScopeInterface::SCOPE_STORES,
                $store->getCode()
            )));
```

2021-08-13 14:45 UTC, peterschriever commented
@progammer-rkt @schmengler I've finally found time to update this PR, implemented the last suggestion from Rajeev.

2021-08-16 05:31 UTC, progammer-rkt approved these changes
Looks good now. Thank you for this PR!

2021-08-16 05:31 UTC, merged